Возможность проставлять ID и версию теста с помощью GET-параметров
profilancegroup/ab-test-system pull request #41
Opened 2022-04-23 12:36 UTC by Swifts522

2022-04-25 06:29 UTC, AlexNovicov requested changes

2022-04-25 06:29 UTC, AlexNovicov commented on src/AB/Cookie/UserTests.php
> +        $ab_test_ids = $ab_test_ids->whereIn('id', array_keys($this->getTests()));
$this->getTests() - $tests_from_cookie

2022-04-25 06:29 UTC, AlexNovicov commented on src/AB/Cookie/UserTests.php
> +            }
Неверные данные и работа продолжается? continue наверное не хватает?

2022-04-25 06:29 UTC, AlexNovicov commented on src/AB/Test/UserTest.php
> +        $received_user_id = $user_id ?? app(AuthSupport::class)->getUserID();
Если $user_id может не передаваться укажи это в аргументах метода

2022-04-25 06:29 UTC, AlexNovicov commented on src/Http/Middleware/AB.php
> +                if(!empty($request->get('ab_set_test')) && !empty($request->get('ab_test_id'))) {
Смысл двух параметров, достаточно же ab_test_id

2022-04-26 17:13 UTC, Swifts522 commented
Поправил

2022-04-27 06:44 UTC, AlexNovicov approved these changes

2022-04-27 06:44 UTC, merged

2022-04-27 06:48 UTC, AlexNovicov commented
Не нашел пул где используется или задачу. Там где нужно залить отпишись пожалуйста